package edu.cornell.cs4321.Operators;

import java.util.ArrayList;
import java.util.List;

import edu.cornell.cs4321.Database.*;
import edu.cornell.cs4321.IO.BinaryTupleReader;
import edu.cornell.cs4321.IO.TupleReader;
import net.sf.jsqlparser.schema.Column;
import net.sf.jsqlparser.schema.Table;

/**
 * ScanOperator that reads files line by line, each line is packaged to a tuple.
 * Each from item or join item has one Scan Operator.
 * @author Chenxi Su cs2238, Hao Qian hq43, Jiangjie Man jm2559
 *
 */
public class ScanOperator extends Operator{
	private TupleReader tr;
	
	/**
	 * Construct a scan operator by table.
	 * @param tableName refers to the table we want to read.
	 */
	public ScanOperator(String tableName){
		tr = new BinaryTupleReader(tableName);
	}

	/**
	 * Construct scan operator by both table and alias 
	 * @param tableName Original table name
	 * @param alias the alias in a query statement of the table
	 */
	public ScanOperator(String tableName, String alias) {
		List<Column> newSchemaList = new ArrayList<Column>();
		List<Column> schemaList = DatabaseCatalog.getSchemaByTable(tableName);
		for(Column c : schemaList){
			Table t = new Table();
			t.setName(alias);
			Column newColumn = new Column();
			newColumn.setTable(t);
			newColumn.setColumnName(c.getColumnName());
			newSchemaList.add(newColumn);
		}
		DatabaseCatalog.setSchemaByTable(tableName, newSchemaList);

		tr = new BinaryTupleReader(tableName);
	}
	
	/**
	 * re-create a file reader to read a table from the beginning.
	 */
	@Override
	public void reset() {
		tr.reset();
	}

	/**
	 * Retrieve next tuple from a file.
	 * If the operator is constructed with alias, then the tuple references to table by alias
	 * @return the next tuple generated by readLine
	 * */
	@Override
	public Tuple getNextTuple() {
		Tuple t = tr.readNextTuple();
		//System.out.println(t);
		return t;
	}
	
	
	
}
